<div>
<img src="https://acortar.link/FrXpm" width="500"/>
</div>

# Machine Learning with Python
# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Cargamos Dataset

In [6]:
dataset = pd.read_csv('Data.csv')


In [7]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [8]:
dataset.shape

(10, 4)

In [ ]:
#X = dataset.iloc[:, :-1].values
#y = dataset.iloc[:, -1].values

In [9]:
dataset.Age

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [10]:
dataset["Age"]

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [17]:
y = dataset["Purchased"]
X = dataset.drop("Purchased", axis=1) #0 hace referencia a filas y 1 a columnas

In [18]:
print(X)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [19]:
print(y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


## Ponemos atención en los datos faltantes

In [20]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [21]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [23]:
imputer.fit(X[["Age","Salary"]])

SimpleImputer()

In [24]:
X[["Age","Salary"]] = imputer.transform(X[["Age","Salary"]])

In [25]:
print(X)

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000


## Encoding Datos Categóricos

### Encoding Variable independiente

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [31]:
pd.DataFrame(X)

0    1    2    3          4             5
0  0.0  1.0  0.0  0.0  44.000000  72000.000000
1  1.0  0.0  0.0  1.0  27.000000  48000.000000
2  1.0  0.0  1.0  0.0  30.000000  54000.000000
3  1.0  0.0  0.0  1.0  38.000000  61000.000000
4  1.0  0.0  1.0  0.0  40.000000  63777.777778
5  0.0  1.0  0.0  0.0  35.000000  58000.000000
6  1.0  0.0  0.0  1.0  38.777778  52000.000000
7  0.0  1.0  0.0  0.0  48.000000  79000.000000
8  1.0  0.0  1.0  0.0  50.000000  83000.000000
9  0.0  1.0  0.0  0.0  37.000000  67000.000000

### Encoding the Dependent Variable

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [33]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Dividir los datos en un conjunto de Train y Test

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [35]:
print(X_train)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.87777778e+01 5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.40000000e+01 7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  2.70000000e+01 4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.50000000e+01 5.80000000e+04]]


In [36]:
print(X_test)

[[1.0e+00 0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [0.0e+00 1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]


In [37]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [38]:
print(y_test)

[0 1]


## Feature Scaling

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [40]:
print(X_train)

[[ 1.          0.          0.          1.29099445 -0.19159184 -1.07812594]
 [ 1.          0.          1.         -0.77459667 -0.01411729 -0.07013168]
 [ 0.          1.          0.         -0.77459667  0.56670851  0.63356243]
 [ 1.          0.          0.          1.29099445 -0.30453019 -0.30786617]
 [ 1.          0.          0.          1.29099445 -1.90180114 -1.42046362]
 [ 0.          1.          0.         -0.77459667  1.14753431  1.23265336]
 [ 1.          0.          1.         -0.77459667  1.43794721  1.57499104]
 [ 0.          1.          0.         -0.77459667 -0.74014954 -0.56461943]]


In [41]:
print(X_test)

[[ 1.          0.          1.         -0.77459667 -1.46618179 -0.9069571 ]
 [ 0.          1.          0.         -0.77459667 -0.44973664  0.20564034]]


### Anexo: Instalar paquetes en jupyter

In [42]:
import sys
!{sys.executable} -m pip install torch