# INTRODUCCIÓN A NUMPY
## machine learning con Python
DS Luis Chacon

![QSL](https://scontent.flim21-1.fna.fbcdn.net/v/t1.0-0/p526x296/150574364_148448927111630_4750160830337593411_o.png?_nc_cat=108&ccb=3&_nc_sid=730e14&_nc_eui2=AeE20XajKLa3M8DN8sEOYXz_zYRPe3wC5BbNhE97fALkFkNLAtiiZgY0xzdXUaE3sKk&_nc_ohc=8fe6b85lkSQAX_9YNk5&_nc_ht=scontent.flim21-1.fna&_nc_tp=30&oh=8d0c95b0ec66518d7f967b141ff74c3c&oe=605C220D)

In [1]:
import sys
import numpy as np

In [2]:
x = [1,2,3]

In [3]:
type(x)

list

In [4]:
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

In [5]:
array_1d

array([1, 2, 3])

# Creación de numpy arrays

In [7]:
array_1d = np.array([4,5, 3])
type(array_1d)

numpy.ndarray

In [8]:
array_1d.ndim

1

In [9]:
array_1d.shape

(3,)

In [10]:
array_1d

array([4, 5, 3])

In [11]:
array_1d.ndim

1

In [12]:
[[1,2,2],
 [2,3,4]]

[[1, 2, 2], [2, 3, 4]]

In [13]:
matriz = np.array([
    [1,2,2],
    [2,3,4]
    ])
matriz

array([[1, 2, 2],
       [2, 3, 4]])

In [14]:
matriz = np.array([
    [ 1,2, 1 ],
    [5, 43, 5]
])

matriz

array([[ 1,  2,  1],
       [ 5, 43,  5]])

In [15]:
matriz.shape

(2, 3)

In [16]:
matriz.ndim

2

`np.eye` crea una matriz identidad de tamaño 3x3

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`np.zeros` crea un array con todos los valores a 0

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

`np.ones` crea un vector de longitud 3 inicializado con todos los valores 1 (${\vec {1}}$)

In [20]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

`np.random` produce un array con valores aleatorios en el intervalo [0, 1)

In [21]:
np.random.random(3)

array([0.5478955 , 0.91078398, 0.53671204])

In [22]:
np.random.random((3,2))

array([[0.52648296, 0.46345472],
       [0.44513257, 0.95460064],
       [0.63729942, 0.30300723]])

podemos leer tambien texto y convertirlo en un np.array

In [27]:
!cat np_text.txt

SyntaxError: invalid syntax (<ipython-input-27-ac4b414ccce6>, line 1)

In [22]:
np.genfromtxt("np_text.txt", delimiter=",")

array([[ 1.,  2.,  3.],
       [43.,  2.,  3.],
       [34.,  1.,  1.],
       [ 0.,  1.,  1.]])

In [23]:
np_text = np.genfromtxt("np_text.txt", delimiter=",")
np_text

array([[ 1.,  2.,  3.],
       [43.,  2.,  3.],
       [34.,  1.,  1.],
       [ 0.,  1.,  1.]])

In [24]:
list([12,3,4])

[12, 3, 4]

In [25]:
[12,3,4]

[12, 3, 4]

In [26]:
np.array([12,3,4])

array([12,  3,  4])

# Ventajas de np.array versus lists

In [27]:
array_1d = np.array([1,2,3])

In [28]:
array_1d = np.array([1,2,3])

In [29]:
array_1d.shape

(3,)

In [30]:
arrar_list = list([1,2,3])

In [31]:
arrar_list

[1, 2, 3]

In [32]:
array_1d

array([1, 2, 3])

In [33]:
lista_2d = [[1222,2222,2223], [5,23,40004]]
lista_2d

[[1222, 2222, 2223], [5, 23, 40004]]

In [34]:
array_2d = np.array([[1222,2222,2223], [5,23,40004]])
array_2d

array([[ 1222,  2222,  2223],
       [    5,    23, 40004]])

In [35]:
sys.getsizeof(lista_2d)

72

In [36]:
sys.getsizeof(array_2d)

136

In [37]:
lista_2d = [[1222,2222,2223], [5,23,40004]]

array_2d = np.array([[1222,2222,2223], [5,23,40004]])

print("Tamaño de la lista en memoria: {} bytes".format(sys.getsizeof(lista_2d)))
print("Tamaño del numpy array en memoria: {} bytes".format(sys.getsizeof(array_2d)))

Tamaño de la lista en memoria: 72 bytes
Tamaño del numpy array en memoria: 136 bytes


No obstante, cuando trabajamos con cantidades grandes, numpy empieza a funcionar mejor

In [38]:
big_list = list(range(1000))
big_array = np.array(range(1000))

print("Tamaño de la lista en memoria: {} bytes".format(sys.getsizeof(big_list)))
print("Tamaño del numpy array en memoria: {} bytes".format(sys.getsizeof(big_array)))

Tamaño de la lista en memoria: 8056 bytes
Tamaño del numpy array en memoria: 4096 bytes


In [39]:
big_lista = list(range(1000))

In [40]:
big_array = np.array(range(1000))

`%%timeit` es un magic de jupyter que evalua el tiempo que tarda una celda en computar, al pasarle el parámetro -n=10 le decimos que queremos que  mida el tiempo corriendo el código 10 veces

In [41]:
%%timeit -n 10
sum(range(10000))

140 µs ± 3.39 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
%%timeit -n 10
np.sum(np.arange(10000))

The slowest run took 31.01 times longer than the fastest. This could mean that an intermediate result is being cached.
70.1 µs ± 136 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Vemos que la operación con np.arrays es 10x más rápida

Para poder utilizar todo el potencial de utilizacion numerica de numpy, todos los elementos del numpy array tienen que ser del mismo tipo, si no lo son, numpy intenta convertir los elementos a un sólo tipo. Numpy hace eso para poder hacer operaciones vectorizadas.

In [48]:
np.array([1.0, 5.4])

array([1. , 5.4])

In [49]:
np.array([1, 3.9])

array([1. , 3.9])

hacemos `dtype` para ver el tipo de datos que almacena el array.

In [50]:
np.array([1, 3.9]).dtype

dtype('float64')

In [51]:
np.array([1, "1"])

array(['1', '1'], dtype='<U11')

Si no puede optimizar un array, numpy lo creara con el tipo `object`, en el que trabajara simplemente con objetos de python.

In [52]:
from datetime import datetime

np.array([1, datetime.utcnow()])

array([1, datetime.datetime(2021, 3, 2, 1, 17, 55, 673235)], dtype=object)

In [53]:
%%timeit
["{}".format(i) for i in range(1000)]

346 µs ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [54]:
f = np.vectorize(lambda x: "{}".format(x))

In [55]:
%%timeit
f(np.arange(1000))

621 µs ± 70.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [56]:
%%timeit
["{}".format(i) for i in np.arange(1000)]

669 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Seleccion por secciones y por indices (slicing e indexing)

In [44]:
matriz_34 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

obtenemos la primera fila igual que con una lista normal

In [45]:
matriz_34[2]

array([ 9, 10, 11, 12])

seleccionamos la 1 y 2 fila

In [62]:
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Seleccionamos el 2 elemento de cada fila (o sea, la segunda columna de la matriz)

In [63]:
matriz_34[:,1]

array([ 2,  6, 10])

al seleccionar secciones no obtenemos copias, sino referencias al mismo array

In [65]:
seccion = matriz_34[:2,:]
seccion

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
print(matriz_34[0,1])
seccion[0, 0] = 0
matriz_34

2


array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Sin embargo, al seleccionar un elemento esto no pasa

In [68]:
seleccion = matriz_34[1,3]
print(seleccion)
seleccion = 100
print(seleccion)
matriz_34

8
100


array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Filtrado

In [69]:
matriz_32 = np.array([[1, 4], [2, 4], [5, 0]])
matriz_32

array([[1, 4],
       [2, 4],
       [5, 0]])

In [70]:
(matriz_32 >= 2)

array([[False,  True],
       [ True,  True],
       [ True, False]])

In [71]:
indice_fitrado = (matriz_32 >= 2)
indice_fitrado

array([[False,  True],
       [ True,  True],
       [ True, False]])

In [72]:
matriz_32[indice_fitrado]

array([4, 2, 4, 5])

In [73]:
matriz_32[(matriz_32 >= 2)]

array([4, 2, 4, 5])

## Aritmetica con numpy arrays

In [74]:
array1 = np.array([[2,3],[0,1]])
array2 = np.array([[23,6],[0,42]])

print(array1)
print(array2)

[[2 3]
 [0 1]]
[[23  6]
 [ 0 42]]


suma elemento a elemento

In [75]:
array1 + array2

array([[25,  9],
       [ 0, 43]])

multiplicación elemento a elemento

In [76]:
array1 * array2

array([[46, 18],
       [ 0, 42]])

Desde python 3.5, podemos usar el simbolo `@` para indicar una multiplicación de matrices (para versiones anteriores se usa la funcion `dot`

In [77]:
array1 @ array2

array([[ 46, 138],
       [  0,  42]])

equivale a 

In [78]:
array1.dot(array2)

array([[ 46, 138],
       [  0,  42]])

# Links

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

https://www.quantopian.com/posts/quantopian-lecture-series-introduction-to-numpy

https://www.datacamp.com/community/tutorials/python-numpy-tutorial#gs.HwYuvYI