# Método K-means

In [2]:
import numpy as np

In [3]:
data = np.random.random(90).reshape(30,3)
data

array([[0.63934265, 0.10380953, 0.15624001],
       [0.72206973, 0.98360224, 0.75511776],
       [0.12475379, 0.33843645, 0.29584029],
       [0.69704418, 0.35221643, 0.76584084],
       [0.66717128, 0.05719224, 0.3397617 ],
       [0.70826986, 0.0905674 , 0.20040256],
       [0.19067169, 0.22909311, 0.96819628],
       [0.86525945, 0.50251953, 0.77865784],
       [0.61813536, 0.04590004, 0.80818176],
       [0.58162125, 0.35888036, 0.20626558],
       [0.11860728, 0.09702462, 0.73975901],
       [0.11152728, 0.5393985 , 0.33283158],
       [0.97831203, 0.5644253 , 0.21736224],
       [0.88469251, 0.9350174 , 0.08738095],
       [0.47534979, 0.45450088, 0.71518283],
       [0.14198432, 0.39097901, 0.2660271 ],
       [0.38156478, 0.84374341, 0.64521058],
       [0.75453411, 0.11914266, 0.5798797 ],
       [0.32008058, 0.38158179, 0.18140683],
       [0.80522251, 0.90320756, 0.40422162],
       [0.70033323, 0.10024004, 0.96915664],
       [0.51456021, 0.94981261, 0.90639016],
       [0.

In [7]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.86525945, 0.50251953, 0.77865784],
       [0.88469251, 0.9350174 , 0.08738095]])

In [8]:
from scipy.cluster.vq import vq

In [9]:
vq(data, clust_centers)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0]),
 array([0.77292433, 0.5024918 , 0.89910215, 0.22594618, 0.655885  ,
        0.72713785, 0.75216718, 0.        , 0.52004166, 0.65476387,
        0.85054612, 0.87648919, 0.40373042, 0.        , 0.39795026,
        0.89350908, 0.60679687, 0.44581462, 0.79618997, 0.32820017,
        0.47467804, 0.58256039, 0.27732718, 0.66805877, 0.21577389,
        0.69664277, 0.61779331, 0.48211549, 0.36159201, 0.25572024]))

In [10]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers)

(array([[0.4836181 , 0.37926403, 0.54709848],
        [0.87056355, 0.81303435, 0.29577813]]),
 0.38520838727055434)

In [12]:
kmeans(data, 2)

(array([[0.56542536, 0.43140448, 0.77016714],
        [0.5329572 , 0.46919437, 0.2733758 ]]),
 0.36297666497006176)