# Clase 2: Notebook

### Subir bases de datos

In [3]:
# \---> /
ruta = "C:/Users/Jhon/OneDrive - Universidad Nacional Federico Villareal/PHYTON/Lambda/sesion 1/"

In [5]:
# subir un csv
# Paquetes.modulos.submodulos.métodos()
# método = función

In [4]:
import pandas as pd

In [6]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]], sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal: str = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, error_bad_lines=True, warn_bad_lines=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read a comma-separated values (csv) file in

In [7]:
aapl = pd.read_csv(ruta + "AAPL.csv"); aapl

Date        Open        High         Low       Close   Adj Close  \
0     2007-12-31   28.500000   28.642857   28.250000   28.297142   25.366503   
1     2008-01-02   28.467142   28.608572   27.507143   27.834286   24.951582   
2     2008-01-03   27.915714   28.198572   27.527143   27.847143   24.963108   
3     2008-01-04   27.350000   27.571428   25.555714   25.721428   23.057547   
4     2008-01-07   25.892857   26.228571   24.318571   25.377142   22.748917   
...          ...         ...         ...         ...         ...         ...   
2514  2017-12-22  174.679993  175.419998  174.500000  175.009995  175.009995   
2515  2017-12-26  170.800003  171.470001  169.679993  170.570007  170.570007   
2516  2017-12-27  170.100006  170.779999  169.710007  170.600006  170.600006   
2517  2017-12-28  171.000000  171.850006  170.479996  171.080002  171.080002   
2518  2017-12-29  170.520004  170.589996  169.220001  169.229996  169.229996   

         Volume  
0     134833300  
1     269794700  
2     210516600  
3     363958000  
4     518048300  
...         ...  
2514   16349400  
2515   33185500  
2516   21498200  
2517   16480200  
2518   25999900  

[2519 rows x 7 columns]

In [9]:
sumaria = pd.read_stata(ruta + "687-Modulo34/sumaria-2019.dta")
sumaria

aÑo mes nconglome conglome vivienda hogar  ubigeo       dominio  \
0      2019  01    007076   005009      041    11  010101  sierra norte   
1      2019  01    007076   005009      056    11  010101  sierra norte   
2      2019  01    007076   005009      084    11  010101  sierra norte   
3      2019  01    007076   005009      098    11  010101  sierra norte   
4      2019  01    007089   005015      018    11  010101  sierra norte   
...     ...  ..       ...      ...      ...   ...     ...           ...   
34560  2019  12    043948   011350      022    11  180101     costa sur   
34561  2019  12    043948   011350      059    11  180101     costa sur   
34562  2019  12    043948   011350      078    11  180101     costa sur   
34563  2019  12    043948   011350      097    11  180101     costa sur   
34564  2019  12    043948   011350      116    11  180101     costa sur   

                             estrato  percepho  ...      gashog24  \
0      de 20,000 a 49,999 habitantes         2  ...  22231.878906   
1      de 20,000 a 49,999 habitantes         3  ...  15891.502930   
2      de 20,000 a 49,999 habitantes         1  ...  16096.603516   
3      de 20,000 a 49,999 habitantes         3  ...  23300.148438   
4      de 20,000 a 49,999 habitantes         3  ...  44742.539062   
...                              ...       ...  ...           ...   
34560  de 50,000 a 99,999 habitantes         2  ...  36245.558594   
34561  de 50,000 a 99,999 habitantes         2  ...  23393.140625   
34562  de 50,000 a 99,999 habitantes         1  ...  17501.556641   
34563  de 50,000 a 99,999 habitantes         1  ...  19168.097656   
34564  de 50,000 a 99,999 habitantes         2  ...  20189.916016   

           gashog26      gashog25      gashog2d  estrsocial        ld  \
0      23015.384766  23149.517578  22366.013672           e  0.815806   
1      16446.982422  16698.673828  16102.574219           e  0.815806   
2      16096.603516  16407.246094  16407.246094           e  0.815806   
3      23588.042969  23652.033203  23364.138672           e  0.815806   
4      44951.917969  45412.714844  45203.335938           d  0.815806   
...             ...           ...           ...         ...       ...   
34560  36245.558594  37693.914062  37693.914062           e  0.854033   
34561  22892.896484  23570.281250  23070.037109           e  0.854033   
34562  19399.974609  19563.822266  17665.404297           e  0.854033   
34563  19168.097656  19194.562500  19194.562500           e  0.854033   
34564  20189.916016  20285.361328  20285.361328           e  0.854033   

            linpe       linea           pobreza   factor07  
0      171.688263  302.621338          no pobre  94.218208  
1      171.688263  302.621338          no pobre  94.218208  
2      171.688263  302.621338          no pobre  94.218208  
3      171.688263  302.621338          no pobre  94.218208  
4      171.688263  302.621338          no pobre  71.583305  
...           ...         ...               ...        ...  
34560  174.192673  345.210449          no pobre  80.257660  
34561  174.192673  345.210449          no pobre  80.257660  
34562  174.192673  345.210449          no pobre  80.257660  
34563  174.192673  345.210449  pobre no extremo  80.257660  
34564  174.192673  345.210449          no pobre  80.257660  

[34565 rows x 158 columns]

In [10]:
students = pd.read_json(ruta + "students.json")
students

id             Name                 Email       Major  year
0   1044      Fran Morton      fran.m@quama.edu  Statistics  2015
1   1035     Kato Mullins       tempor@giat.com   Marketing  2014
2   1046    Jordan Keller         Cum@gmail.com   Chemistry  2014
3   1084    Macey Simpson  eu@famesacturpis.com     Finance  2016
4   1010    Deanna Ortega   Dea.Ortega@velit.ca   Chemistry  2016
5   1096        Joe Eaton        je@euismod.org         MIS  2014
6   1051  Yoko Washington      yoko@yahoo.co.uk   Marketing  2017
7   1074    Ebony Farrell  efarrella@gravid.com   Chemistry  2017
8   1034   Quinn Delacruz      Delacruz@shu.edu   Marketing  2017
9   1028   Magee Humphrey   mageehump@gmail.com     Physics  2016
10  1003   Kaitlin Cooper   kcooper@hotmail.com  Accounting  2014
11  1021       Carson Roy        croy@yahoo.com     History  2017

In [11]:
url = "https://estadisticas.bcrp.gob.pe/estadisticas/series/diarias/resultados/PD04719XD/html"

In [15]:
tbond10y = pd.read_html(url)
tbond10y

[                                                   0  \
 0  Consulta de SeriesPor CategoríaPor FrecuenciaP...   
 
                                                    1  
 0  Desde:  Hasta:  Bonos del Tesoro EE.UU. - 10 a...  ,
         Fecha  \
 0     14Ene97   
 1     15Ene97   
 2     16Ene97   
 3     17Ene97   
 4     20Ene97   
 ...       ...   
 6248  25Dic20   
 6249  28Dic20   
 6250  29Dic20   
 6251  30Dic20   
 6252  31Dic20   
 
      Tasas de interés internacionales - Bonos del Tesoro EE.UU. - 10 años (%)  
 0                                                   6.5                        
 1                                                   6.5                        
 2                                                   6.6                        
 3                                                   6.5                        
 4                                                   6.5                        
 ...                                                 ...           

In [16]:
tbond10y[1]

Fecha  \
0     14Ene97   
1     15Ene97   
2     16Ene97   
3     17Ene97   
4     20Ene97   
...       ...   
6248  25Dic20   
6249  28Dic20   
6250  29Dic20   
6251  30Dic20   
6252  31Dic20   

     Tasas de interés internacionales - Bonos del Tesoro EE.UU. - 10 años (%)  
0                                                   6.5                        
1                                                   6.5                        
2                                                   6.6                        
3                                                   6.5                        
4                                                   6.5                        
...                                                 ...                        
6248                                               n.d.                        
6249                                                0.9                        
6250                                                0.9                        
6251                                                0.9                        
6252                                                0.9                        

[6253 rows x 2 columns]

In [20]:
# Case sensity 
sumaria_spss = pd.read_spss(ruta + "687-Modulo34/sumaria-2019.sav") 
sumaria_spss

PyreadstatError: File C:/Users/Jhon/OneDrive - Universidad Nacional Federico Villareal/PHYTON/Lambda/sesion 1/687-Modulo34/sumaria-2019.sav does not exist!

In [30]:
from dbfread import DBF

In [31]:
airport = DBF(ruta + "airports.dbf")

### Algebra lineal

In [32]:
import numpy as np

In [33]:
a1 = np.array([1,3,5,7,8,12]); a1

array([ 1,  3,  5,  7,  8, 12])

In [35]:
a2 = np.array([[1,3,5,7,8,12],[1,3,5,7,8,12],[1,3,5,7,8,12]]); a2

array([[ 1,  3,  5,  7,  8, 12],
       [ 1,  3,  5,  7,  8, 12],
       [ 1,  3,  5,  7,  8, 12]])

In [36]:
m1 = np.matrix([[1,3,5,7,8,12],[1,3,5,7,8,12],[1,3,5,7,8,12]]); m1

matrix([[ 1,  3,  5,  7,  8, 12],
        [ 1,  3,  5,  7,  8, 12],
        [ 1,  3,  5,  7,  8, 12]])

In [40]:
# paquete.modulo.metodo
s1 = np.random.randn(1,10); s1
s1

array([[ 1.5311953 , -0.23333336, -0.10676005, -0.82958931, -0.20542767,
         0.3559693 ,  1.01245175, -1.98286915, -0.05719797, -0.72457863]])

In [41]:
s2 = np.random.randn(10)
s2

array([ 0.24876256, -1.74486946, -0.433322  , -0.879228  ,  1.18794293,
        0.60648462,  0.1875346 ,  0.27439771,  1.89359642,  0.12565164])

In [42]:
# Matrices
A = np.matrix([[1,2,6],[2,6,7],[6,8,9]])

In [43]:
# import numpy as np
# from numpy import linalg
# from numpy import linalg as la

In [44]:
np.linalg.det(A)

-74.00000000000003

In [45]:
from numpy import linalg

In [46]:
linalg.det(A)

-74.00000000000003

In [47]:
from numpy import linalg as la

In [48]:
la.det(A)

-74.00000000000003

In [49]:
la.inv(A)

matrix([[ 0.02702703, -0.40540541,  0.2972973 ],
        [-0.32432432,  0.36486486, -0.06756757],
        [ 0.27027027, -0.05405405, -0.02702703]])

In [50]:
x, y = la.eig(A)
x, y

(array([17.3126619 , -2.82545487,  1.51279297]),
 matrix([[-0.34841847, -0.76079411,  0.60937882],
         [-0.53698845, -0.28863588, -0.73510516],
         [-0.76827597,  0.58127588,  0.29711591]]))

In [51]:
B = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
A, B

(matrix([[1, 2, 6],
         [2, 6, 7],
         [6, 8, 9]]),
 matrix([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [53]:
A@B

matrix([[ 51,  60,  69],
        [ 75,  90, 105],
        [101, 124, 147]])

In [54]:
D = np.matrix([[2,-1,-2],[4,5,6],[7,-8,9]])

In [55]:
import scipy.linalg as la

In [57]:
m1 = la.lu(D)

In [58]:
m1

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.57142857, 1.        , 0.        ],
        [0.28571429, 0.13432836, 1.        ]]),
 array([[ 7.        , -8.        ,  9.        ],
        [ 0.        ,  9.57142857,  0.85714286],
        [ 0.        ,  0.        , -4.68656716]]))

In [59]:
m2 = la.qr(D)
m2

(array([[-0.24077171, -0.01220665, -0.97050501],
        [-0.48154341, -0.86667212,  0.13036635],
        [-0.84270097,  0.49872882,  0.20279209]]),
 array([[-8.30662386,  4.57466242, -9.99202581],
        [ 0.        , -8.31098452, -0.68705999],
        [ 0.        ,  0.        ,  4.54833693]]))

### Cálculo