# Clase 2: Notebook

### Subir bases de datos

In [4]:
# \ --> /
ruta = "C:/Users/HBP/Desktop/Python Set/"

In [ ]:
# Subir un csv
# paquetes.modulos.submodulos.métodos()
# método = función

In [5]:
import pandas as pd

In [6]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]], sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal: str = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, error_bad_lines=True, warn_bad_lines=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read a comma-separated values (csv) file in

In [9]:
aapl = pd.read_csv(ruta + "AAPL.csv"); aapl

Date        Open        High         Low       Close   Adj Close  \
0     2007-12-31   28.500000   28.642857   28.250000   28.297142   25.366503   
1     2008-01-02   28.467142   28.608572   27.507143   27.834286   24.951582   
2     2008-01-03   27.915714   28.198572   27.527143   27.847143   24.963108   
3     2008-01-04   27.350000   27.571428   25.555714   25.721428   23.057547   
4     2008-01-07   25.892857   26.228571   24.318571   25.377142   22.748917   
...          ...         ...         ...         ...         ...         ...   
2514  2017-12-22  174.679993  175.419998  174.500000  175.009995  175.009995   
2515  2017-12-26  170.800003  171.470001  169.679993  170.570007  170.570007   
2516  2017-12-27  170.100006  170.779999  169.710007  170.600006  170.600006   
2517  2017-12-28  171.000000  171.850006  170.479996  171.080002  171.080002   
2518  2017-12-29  170.520004  170.589996  169.220001  169.229996  169.229996   

         Volume  
0     134833300  
1     269794700  
2     210516600  
3     363958000  
4     518048300  
...         ...  
2514   16349400  
2515   33185500  
2516   21498200  
2517   16480200  
2518   25999900  

[2519 rows x 7 columns]

In [10]:
aapl = pd.read_csv(ruta + "AAPL.csv")
aapl

Date        Open        High         Low       Close   Adj Close  \
0     2007-12-31   28.500000   28.642857   28.250000   28.297142   25.366503   
1     2008-01-02   28.467142   28.608572   27.507143   27.834286   24.951582   
2     2008-01-03   27.915714   28.198572   27.527143   27.847143   24.963108   
3     2008-01-04   27.350000   27.571428   25.555714   25.721428   23.057547   
4     2008-01-07   25.892857   26.228571   24.318571   25.377142   22.748917   
...          ...         ...         ...         ...         ...         ...   
2514  2017-12-22  174.679993  175.419998  174.500000  175.009995  175.009995   
2515  2017-12-26  170.800003  171.470001  169.679993  170.570007  170.570007   
2516  2017-12-27  170.100006  170.779999  169.710007  170.600006  170.600006   
2517  2017-12-28  171.000000  171.850006  170.479996  171.080002  171.080002   
2518  2017-12-29  170.520004  170.589996  169.220001  169.229996  169.229996   

         Volume  
0     134833300  
1     269794700  
2     210516600  
3     363958000  
4     518048300  
...         ...  
2514   16349400  
2515   33185500  
2516   21498200  
2517   16480200  
2518   25999900  

[2519 rows x 7 columns]

In [12]:
sumaria = pd.read_stata(ruta + "687-Modulo34/sumaria-2019.dta")
sumaria

aÑo mes nconglome conglome vivienda hogar  ubigeo       dominio  \
0      2019  01    007076   005009      041    11  010101  sierra norte   
1      2019  01    007076   005009      056    11  010101  sierra norte   
2      2019  01    007076   005009      084    11  010101  sierra norte   
3      2019  01    007076   005009      098    11  010101  sierra norte   
4      2019  01    007089   005015      018    11  010101  sierra norte   
...     ...  ..       ...      ...      ...   ...     ...           ...   
34560  2019  12    043948   011350      022    11  180101     costa sur   
34561  2019  12    043948   011350      059    11  180101     costa sur   
34562  2019  12    043948   011350      078    11  180101     costa sur   
34563  2019  12    043948   011350      097    11  180101     costa sur   
34564  2019  12    043948   011350      116    11  180101     costa sur   

                             estrato  percepho  ...      gashog24  \
0      de 20,000 a 49,999 habitantes         2  ...  22231.878906   
1      de 20,000 a 49,999 habitantes         3  ...  15891.502930   
2      de 20,000 a 49,999 habitantes         1  ...  16096.603516   
3      de 20,000 a 49,999 habitantes         3  ...  23300.148438   
4      de 20,000 a 49,999 habitantes         3  ...  44742.539062   
...                              ...       ...  ...           ...   
34560  de 50,000 a 99,999 habitantes         2  ...  36245.558594   
34561  de 50,000 a 99,999 habitantes         2  ...  23393.140625   
34562  de 50,000 a 99,999 habitantes         1  ...  17501.556641   
34563  de 50,000 a 99,999 habitantes         1  ...  19168.097656   
34564  de 50,000 a 99,999 habitantes         2  ...  20189.916016   

           gashog26      gashog25      gashog2d  estrsocial        ld  \
0      23015.384766  23149.517578  22366.013672           e  0.815806   
1      16446.982422  16698.673828  16102.574219           e  0.815806   
2      16096.603516  16407.246094  16407.246094           e  0.815806   
3      23588.042969  23652.033203  23364.138672           e  0.815806   
4      44951.917969  45412.714844  45203.335938           d  0.815806   
...             ...           ...           ...         ...       ...   
34560  36245.558594  37693.914062  37693.914062           e  0.854033   
34561  22892.896484  23570.281250  23070.037109           e  0.854033   
34562  19399.974609  19563.822266  17665.404297           e  0.854033   
34563  19168.097656  19194.562500  19194.562500           e  0.854033   
34564  20189.916016  20285.361328  20285.361328           e  0.854033   

            linpe       linea           pobreza   factor07  
0      171.688263  302.621338          no pobre  94.218208  
1      171.688263  302.621338          no pobre  94.218208  
2      171.688263  302.621338          no pobre  94.218208  
3      171.688263  302.621338          no pobre  94.218208  
4      171.688263  302.621338          no pobre  71.583305  
...           ...         ...               ...        ...  
34560  174.192673  345.210449          no pobre  80.257660  
34561  174.192673  345.210449          no pobre  80.257660  
34562  174.192673  345.210449          no pobre  80.257660  
34563  174.192673  345.210449  pobre no extremo  80.257660  
34564  174.192673  345.210449          no pobre  80.257660  

[34565 rows x 158 columns]

In [14]:
students = pd.read_json(ruta + "students.json")
students

id             Name                 Email       Major  year
0   1044      Fran Morton      fran.m@quama.edu  Statistics  2015
1   1035     Kato Mullins       tempor@giat.com   Marketing  2014
2   1046    Jordan Keller         Cum@gmail.com   Chemistry  2014
3   1084    Macey Simpson  eu@famesacturpis.com     Finance  2016
4   1010    Deanna Ortega   Dea.Ortega@velit.ca   Chemistry  2016
5   1096        Joe Eaton        je@euismod.org         MIS  2014
6   1051  Yoko Washington      yoko@yahoo.co.uk   Marketing  2017
7   1074    Ebony Farrell  efarrella@gravid.com   Chemistry  2017
8   1034   Quinn Delacruz      Delacruz@shu.edu   Marketing  2017
9   1028   Magee Humphrey   mageehump@gmail.com     Physics  2016
10  1003   Kaitlin Cooper   kcooper@hotmail.com  Accounting  2014
11  1021       Carson Roy        croy@yahoo.com     History  2017

In [15]:
url = "https://estadisticas.bcrp.gob.pe/estadisticas/series/diarias/resultados/PD04719XD/html"

In [17]:
tbond10y = pd.read_html(url)
tbond10y.__class__

[                                                   0  \
 0  Consulta de SeriesPor CategoríaPor FrecuenciaP...   
 
                                                    1  
 0  Desde:  Hasta:  Bonos del Tesoro EE.UU. - 10 a...  ,
         Fecha  \
 0     14Ene97   
 1     15Ene97   
 2     16Ene97   
 3     17Ene97   
 4     20Ene97   
 ...       ...   
 6177  17Set20   
 6178  18Set20   
 6179  21Set20   
 6180  22Set20   
 6181  23Set20   
 
      Tasas de interés internacionales - Bonos del Tesoro EE.UU. - 10 años (%)  
 0                                                   6.5                        
 1                                                   6.5                        
 2                                                   6.6                        
 3                                                   6.5                        
 4                                                   6.5                        
 ...                                                 ...           

In [18]:
tbond10y[1]

Fecha  \
0     14Ene97   
1     15Ene97   
2     16Ene97   
3     17Ene97   
4     20Ene97   
...       ...   
6177  17Set20   
6178  18Set20   
6179  21Set20   
6180  22Set20   
6181  23Set20   

     Tasas de interés internacionales - Bonos del Tesoro EE.UU. - 10 años (%)  
0                                                   6.5                        
1                                                   6.5                        
2                                                   6.6                        
3                                                   6.5                        
4                                                   6.5                        
...                                                 ...                        
6177                                                0.7                        
6178                                                0.7                        
6179                                                0.7                        
6180                                                0.7                        
6181                                                0.7                        

[6182 rows x 2 columns]

In [20]:
# Case sensity
sumaria_spss = pd.read_spss(ruta + "687-Modulo34/Sumaria-2019.sav")
sumaria_spss

AÑO MES NCONGLOME CONGLOME VIVIENDA HOGAR  UBIGEO       DOMINIO  \
0      2019  01    007076   005009      041    11  010101  sierra norte   
1      2019  01    007076   005009      056    11  010101  sierra norte   
2      2019  01    007076   005009      084    11  010101  sierra norte   
3      2019  01    007076   005009      098    11  010101  sierra norte   
4      2019  01    007089   005015      018    11  010101  sierra norte   
...     ...  ..       ...      ...      ...   ...     ...           ...   
34560  2019  12    043948   011350      022    11  180101     costa sur   
34561  2019  12    043948   011350      059    11  180101     costa sur   
34562  2019  12    043948   011350      078    11  180101     costa sur   
34563  2019  12    043948   011350      097    11  180101     costa sur   
34564  2019  12    043948   011350      116    11  180101     costa sur   

                             ESTRATO  PERCEPHO  ...      GASHOG24  \
0      de 20,000 a 49,999 habitantes       2.0  ...  22231.878906   
1      de 20,000 a 49,999 habitantes       3.0  ...  15891.502930   
2      de 20,000 a 49,999 habitantes       1.0  ...  16096.603516   
3      de 20,000 a 49,999 habitantes       3.0  ...  23300.148438   
4      de 20,000 a 49,999 habitantes       3.0  ...  44742.539062   
...                              ...       ...  ...           ...   
34560  de 50,000 a 99,999 habitantes       2.0  ...  36245.558594   
34561  de 50,000 a 99,999 habitantes       2.0  ...  23393.140625   
34562  de 50,000 a 99,999 habitantes       1.0  ...  17501.556641   
34563  de 50,000 a 99,999 habitantes       1.0  ...  19168.097656   
34564  de 50,000 a 99,999 habitantes       2.0  ...  20189.916016   

           GASHOG26      GASHOG25      GASHOG2D  ESTRSOCIAL        LD  \
0      23015.384766  23149.517578  22366.013672           E  0.815806   
1      16446.982422  16698.673828  16102.574219           E  0.815806   
2      16096.603516  16407.246094  16407.246094           E  0.815806   
3      23588.042969  23652.033203  23364.138672           E  0.815806   
4      44951.917969  45412.714844  45203.335938           D  0.815806   
...             ...           ...           ...         ...       ...   
34560  36245.558594  37693.914062  37693.914062           E  0.854033   
34561  22892.896484  23570.281250  23070.037109           E  0.854033   
34562  19399.974609  19563.822266  17665.404297           E  0.854033   
34563  19168.097656  19194.562500  19194.562500           E  0.854033   
34564  20189.916016  20285.361328  20285.361328           E  0.854033   

            LINPE       LINEA           POBREZA   FACTOR07  
0      171.688263  302.621338          No Pobre  94.218208  
1      171.688263  302.621338          No Pobre  94.218208  
2      171.688263  302.621338          No Pobre  94.218208  
3      171.688263  302.621338          No Pobre  94.218208  
4      171.688263  302.621338          No Pobre  71.583305  
...           ...         ...               ...        ...  
34560  174.192673  345.210449          No Pobre  80.257660  
34561  174.192673  345.210449          No Pobre  80.257660  
34562  174.192673  345.210449          No Pobre  80.257660  
34563  174.192673  345.210449  Pobre No Extremo  80.257660  
34564  174.192673  345.210449          No Pobre  80.257660  

[34565 rows x 158 columns]

In [25]:
from dbfread import DBF

In [26]:
from dbfread import DBF
airport = DBF(ruta + "airports.dbf")
airport

<unloaded DBF table 'C:/Users/HBP/Desktop/Python Set\\airports.dbf'>

### Algebra lineal

In [27]:
import numpy as np

In [29]:
a1 = np.array([1,3,5,7,8,12]); a1

array([ 1,  3,  5,  7,  8, 12])

In [32]:
a2 = np.array([[1,3,5,7,8,12], [11,31,51,71,81,121], [51,53,55,57,58,512]])
a2

array([[  1,   3,   5,   7,   8,  12],
       [ 11,  31,  51,  71,  81, 121],
       [ 51,  53,  55,  57,  58, 512]])

In [33]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [34]:
m1 = np.matrix([[  1,   3,   5,   7,   8,  12],
       [ 11,  31,  51,  71,  81, 121],
       [ 51,  53,  55,  57,  58, 512]])

In [35]:
m1

matrix([[  1,   3,   5,   7,   8,  12],
        [ 11,  31,  51,  71,  81, 121],
        [ 51,  53,  55,  57,  58, 512]])

In [39]:
# paquete.modulo.metodo
s1 = np.random.randn(1,10)
s1

array([[-0.11759559,  1.23628079,  3.04401537,  1.25630614, -0.17731151,
         0.27765668,  0.01261297, -0.13185069,  0.1868907 ,  0.94208671]])

In [40]:
s2 = np.random.random(10)
s2

array([0.55112582, 0.70757952, 0.53247524, 0.65419969, 0.10490919,
       0.49123747, 0.90739225, 0.38915489, 0.54171434, 0.97100825])

In [36]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
    
    Paramete

In [41]:
# Matrices

In [42]:
A = np.matrix([[1,2,6],[2,5,7],[6,8,9]])

In [ ]:
# import numpy as np
# from numpy import linalg
# from numpy import linalg as la

In [43]:
np.linalg.det(A)

-46.99999999999999

In [44]:
from numpy import linalg

In [45]:
linalg.det(A)

-46.99999999999999

In [46]:
from numpy import linalg as la

In [47]:
la.det(A)

-46.99999999999999

In [48]:
la.inv(A)

matrix([[ 0.23404255, -0.63829787,  0.34042553],
        [-0.5106383 ,  0.57446809, -0.10638298],
        [ 0.29787234, -0.08510638, -0.0212766 ]])

In [52]:
x, y = la.eig(A)
x, y

(array([17.01248247, -2.94922831,  0.93674584]),
 matrix([[-0.35654034, -0.73000677,  0.64959149],
         [-0.51399605, -0.33893863, -0.72329633],
         [-0.78018398,  0.59347344,  0.23425055]]))

In [53]:
help(la.eig)

Help on function eig in module numpy.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.
    
    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed
    
    Returns
    -------
    w : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs
    
    v : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``v[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``w[i]``.
    
    Raises
    ------
    LinAlgError
        If the eigenvalue computation does not converg

In [54]:
B = np.matrix([[9,4,6],[3,4,1],[3,3,3]])

In [55]:
A, B

(matrix([[1, 2, 6],
         [2, 5, 7],
         [6, 8, 9]]),
 matrix([[9, 4, 6],
         [3, 4, 1],
         [3, 3, 3]]))

In [56]:
A@B

matrix([[ 33,  30,  26],
        [ 54,  49,  38],
        [105,  83,  71]])

In [65]:
D = np.matrix([[2,-1,-2],[-4,6,3],[-4,-2,8]])

In [58]:
import scipy.linalg as la

In [66]:
m1 = la.lu(D)

In [67]:
m1

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 1.  ,  1.  ,  0.  ],
        [-0.5 , -0.25,  1.  ]]),
 array([[-4.  ,  6.  ,  3.  ],
        [ 0.  , -8.  ,  5.  ],
        [ 0.  ,  0.  ,  0.75]]))

In [69]:
m2 = la.qr(D)
m2

(array([[-3.33333333e-01,  1.48029737e-16,  9.42809042e-01],
        [ 6.66666667e-01, -7.07106781e-01,  2.35702260e-01],
        [ 6.66666667e-01,  7.07106781e-01,  2.35702260e-01]]),
 array([[-6.        ,  3.        ,  8.        ],
        [ 0.        , -5.65685425,  3.53553391],
        [ 0.        ,  0.        ,  0.70710678]]))

### Cálculo